import CardContainer1 from "./card-container1";

const LocationCard = () => {
  return (
    <div className="self-stretch flex flex-row flex-wrap items-start justify-center text-left text-[14.51px] text-gray-700 font-body-large-400">
      <div className="flex-1 flex flex-row flex-wrap items-start justify-center gap-[8px]">
        <CardContainer1
          propertyImage="/unsplashrlwe8f8anoc4@2x.png"
          car="/car2.svg"
          bathtub="/bathtub1.svg"
          arrowsOut="/arrowsout3.svg"
          ellipse1="/ellipse-1@2x.png"
          shareNetwork="/sharenetwork2.svg"
          heart="/heart1.svg"
          plus="/plus3.svg"
        />
        <CardContainer1
          propertyImage="/unsplashrlwe8f8anoc5@2x.png"
          car="/car3.svg"
          bathtub="/bathtub2.svg"
          arrowsOut="/arrowsout3.svg"
          ellipse1="/ellipse-1@2x.png"
          shareNetwork="/sharenetwork3.svg"
          heart="/heart2.svg"
          plus="/plus4.svg"
        />
        <CardContainer1
          propertyImage="/unsplashrlwe8f8anoc6@2x.png"
          car="/car4.svg"
          bathtub="/bathtub3.svg"
          arrowsOut="/arrowsout3.svg"
          ellipse1="/ellipse-1@2x.png"
          shareNetwork="/sharenetwork2.svg"
          heart="/heart1.svg"
          plus="/plus3.svg"
        />
        <CardContainer1
          propertyImage="/unsplashrlwe8f8anoc7@2x.png"
          car="/car3.svg"
          bathtub="/bathtub2.svg"
          arrowsOut="/arrowsout3.svg"
          ellipse1="/ellipse-1@2x.png"
          shareNetwork="/sharenetwork4.svg"
          heart="/heart2.svg"
          plus="/plus5.svg"
        />
        <CardContainer1
          propertyImage="/unsplashrlwe8f8anoc4@2x.png"
          car="/car2.svg"
          bathtub="/bathtub1.svg"
          arrowsOut="/arrowsout3.svg"
          ellipse1="/ellipse-1@2x.png"
          shareNetwork="/sharenetwork4.svg"
          heart="/heart.svg"
          plus="/plus2.svg"
        />
        <CardContainer1
          propertyImage="/unsplashrlwe8f8anoc8@2x.png"
          car="/car5.svg"
          bathtub="/bathtub4.svg"
          arrowsOut="/arrowsout4.svg"
          ellipse1="/ellipse-11@2x.png"
          shareNetwork="/sharenetwork5.svg"
          heart="/heart3.svg"
          plus="/plus6.svg"
        />
        <CardContainer1
          propertyImage="/unsplashrlwe8f8anoc9@2x.png"
          car="/car6.svg"
          bathtub="/bathtub5.svg"
          arrowsOut="/arrowsout4.svg"
          ellipse1="/ellipse-11@2x.png"
          shareNetwork="/sharenetwork6.svg"
          heart="/heart4.svg"
          plus="/plus7.svg"
        />
        <CardContainer1
          propertyImage="/unsplashrlwe8f8anoc10@2x.png"
          car="/car5.svg"
          bathtub="/bathtub4.svg"
          arrowsOut="/arrowsout4.svg"
          ellipse1="/ellipse-11@2x.png"
          shareNetwork="/sharenetwork7.svg"
          heart="/heart3.svg"
          plus="/plus8.svg"
        />
      </div>
    </div>
  );
};

export default LocationCard;
